# Generated by Django 3.1.5 on 2021-01-12 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0006_auto_20201227_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='done_flag',
            field=models.BooleanField(null=True),
        ),
    ]
